/**
 * One-shot provisioner for the RLS test branch. NEVER run against prod.
 *
 * Given the branch OWNER connection string (env RLS_OWNER_URL), this:
 *   1. creates the least-privilege `app_user` role with a freshly generated password
 *   2. applies prisma/rls.sql (grants + policies)
 *   3. writes RLS_OWNER_URL + RLS_APP_URL (app_user, pooled) into .env  (gitignored)
 *
 * The generated password is written to disk only — it is never printed to stdout.
 *
 * Usage (PowerShell):
 *   $env:RLS_OWNER_URL="postgresql://neondb_owner:...-pooler.../neondb?sslmode=require";
 *   npx tsx scripts/rls-provision.ts
 */
import { PrismaClient } from "@prisma/client";
import { randomBytes } from "node:crypto";
import { readFileSync, appendFileSync } from "node:fs";
import { join } from "node:path";

const OWNER = process.env.RLS_OWNER_URL;
if (!OWNER) {
  console.error("Set RLS_OWNER_URL to the BRANCH owner connection string.");
  process.exit(2);
}

// DDL (CREATE ROLE / ALTER TABLE) is happiest on the direct (non-pooled) endpoint.
const ownerDirect = OWNER.replace("-pooler.", ".");

// URL-safe password (base64url = [A-Za-z0-9_-], no chars that need escaping in a URL).
const password = randomBytes(24).toString("base64url");

// Build the app_user pooled URL by swapping the credentials in the owner (pooled) URL.
function withCreds(url: string, user: string, pass: string): string {
  const u = new URL(url);
  u.username = user;
  u.password = pass;
  return u.toString();
}
const ownerPooled = OWNER.includes("-pooler.") ? OWNER : OWNER.replace(".", "-pooler.");
const appPooled = withCreds(ownerPooled, "app_user", password);

const db = new PrismaClient({ datasourceUrl: ownerDirect });

async function main() {
  // 1. Create or reset the role's password (idempotent).
  const exists = await db.$queryRawUnsafe<{ c: bigint }[]>(
    `SELECT count(*)::int AS c FROM pg_roles WHERE rolname = 'app_user'`
  );
  const roleExists = Number(exists[0].c) > 0;
  // Password is generated locally from [A-Za-z0-9_-]; safe to inline (no quotes/injection).
  if (roleExists) {
    await db.$executeRawUnsafe(`ALTER ROLE app_user WITH LOGIN PASSWORD '${password}'`);
    console.log("app_user already existed — rotated its password.");
  } else {
    await db.$executeRawUnsafe(`CREATE ROLE app_user WITH LOGIN PASSWORD '${password}'`);
    console.log("Created role app_user.");
  }

  // 2. Apply prisma/rls.sql (grants + policies), statement by statement.
  const sql = readFileSync(join(process.cwd(), "prisma", "rls.sql"), "utf8");
  const statements = sql
    .split(/;\s*$/m)
    .map((s) => s.trim())
    .filter((s) => s && !s.split("\n").every((l) => !l.trim() || l.trim().startsWith("--")));
  for (const stmt of statements) await db.$executeRawUnsafe(stmt);
  console.log(`Applied prisma/rls.sql (${statements.length} statements).`);

  // 3. Persist the test connection strings to .env (gitignored) for the harness + smoke test.
  const block =
    `\n# ── RLS branch test (generated by scripts/rls-provision.ts — do NOT commit) ──\n` +
    `RLS_OWNER_URL="${OWNER}"\n` +
    `RLS_APP_URL="${appPooled}"\n`;
  appendFileSync(join(process.cwd(), ".env"), block);
  console.log("Wrote RLS_OWNER_URL + RLS_APP_URL to .env (password on disk only, not printed).");
  console.log("\nNext: npm run test:rls");
}

main()
  .catch((e) => {
    console.error("Provision failed:", e);
    process.exitCode = 1;
  })
  .finally(() => db.$disconnect());
